services:
  server:
    container_name: url-shortener-server
    build: .
    profiles: ["app"]
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: redis
      REDIS_PORT: 6379
      SERVER_PORT: 8080
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: url_shortener_db
      DB_HOST: postgres
      DB_PORT: 5432
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    depends_on:
      - redis
      - postgres
      - kafka
    networks:
      - backend-net
    volumes:
      - ./assets:/app/assets

  redis:
    container_name: redis
    image: "redis:alpine"
    profiles: ["app", "infra"]
    ports:
      - "6379:6379"
    networks:
      - backend-net

  postgres:
    container_name: postgres
    image: "postgres:16-alpine"
    profiles: ["app", "infra"]
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-net

  kafka:
    container_name: kafka
    image: "bitnamilegacy/kafka:3.9.0-debian-12-r9"
    profiles: ["app", "infra"]
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge

volumes:
  postgres_data:
  kafka_data:
