services:
  server:
    container_name: url-shortener-server
    build: .
    profiles: ["app"]
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: redis
      REDIS_PORT: 6379
      SERVER_PORT: 8080
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: url_shortener_db
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - redis
      - postgres
    networks:
      - backend-net

  redis:
    container_name: redis
    image: "redis:alpine"
    profiles: ["app", "infra"]
    ports:
      - "6379:6379"
    networks:
      - backend-net

  postgres:
    container_name: postgres
    image: "postgres:16-alpine"
    profiles: ["app", "infra"]
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge

volumes:
  postgres_data:
